config/routes.rb
Rails.application.routes.draw do
  mount Faultline::Engine, at: "/faultline"

  namespace :admin do
    root "dashboard#index"
    resources :users
  end

  resources :chattels
  root "dashboard#index"

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resources :transactions
  namespace :transactions do
    resources :imports, only: [ :create ]
  end
  resources :credit, controller: "transactions", type: "Transaction"
  resources :debit, controller: "transactions", type: "Transaction"
  resources :transfer, controller: "transactions", type: "Transaction"
  resources :accounts do
    scope module: "accounts" do
      resource :transactions_bulk, only: [ :update ]
    end
  end
  resources :categories
  get "dashboard/index"
  get "todo", to: "todos#index", as: :todo

  get "up" => "rails/health#show", as: :rails_health_check
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/transactions/imports_controller.rb
require "csv"

# CSV import operations for transactions
class Transactions::ImportsController < ApplicationController
  # Creates a new transaction import from a CSV file
  #
  # @return [void]
  def create
    csv = imports_params[:csv]

    # Validate file presence
    if csv.blank?
      flash[:alert] = t('.no_file')
      return redirect_to transactions_path
    end

    # Validate file type
    unless csv.content_type.in?(['text/csv', 'text/plain', 'application/vnd.ms-excel'])
      flash[:alert] = t('.invalid_file_type')
      return redirect_to transactions_path
    end

    # Validate file size
    if csv.size > 5.megabytes
      flash[:alert] = t('.file_too_large')
      return redirect_to transactions_path
    end

    # Process CSV with error tracking
    failed = 0
    CSV.foreach(csv.tempfile.path, col_sep: ";") do |row|
      Importing::ING::ImportJob.perform_now(row)
    rescue StandardError => e
      Rails.logger.warn "Failed to import row: #{e.message}"
      failed += 1
    end

    flash[:notice] = t('.import_complete')
    flash[:alert] = t('.import_failed', count: failed) if failed.positive?

    redirect_to transactions_path
  end

  private

  def imports_params
    params.permit(:csv)
  end
end

app/controllers/transactions_controller.rb
# Manages transaction resources
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # Lists all transactions with optional category filtering
  #
  # @action GET
  # @route /transactions
  # @return [void]
  def index
    transactions = Transaction.ordered
    transactions = transactions.where(category: nil) if params[:filter] == "no_category"

    @pagy, @transactions = pagy transactions.order(interest_at: :desc), items: 20
  end

  # Displays a single transaction
  #
  # @action GET
  # @route /transactions/:id
  # @return [void]
  def show; end

  # Renders form for creating a new transaction
  #
  # @action GET
  # @route /transactions/new
  # @return [void]
  def new
    @transaction = Transaction.new
  end

  # Renders form for editing a transaction
  #
  # @action GET
  # @route /transactions/:id/edit
  # @return [void]
  def edit; end

  # Creates a new transaction
  #
  # @action POST
  # @route /transactions
  # @return [void]
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: t(".success") }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # Updates a transaction
  #
  # @action PATCH
  # @route /transactions/:id
  # @return [void]
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: t(".success") }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # Deletes a transaction
  #
  # @action DELETE
  # @route /transactions/:id
  # @return [void]
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: t(".success") }
      format.json { head :no_content }
    end
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def transaction_params
    params.require(:transaction).permit(
      :booked_at,
      :interest_at,
      :category_id,
      :note
    )
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%# Ensure disabled local has a default value when not provided %>
<% disabled = local_assigns.key?(:disabled) ? local_assigns[:disabled] : nil %>

<section>
  <%= form_for @transaction do |f| %>
    <% if @transaction.errors.any? %>
      <div id="error_explanation">
        <h2><%= t("errors.template.header", count: @transaction.errors.count, model: @transaction.model_name.human) %></h2>
        <ul>
          <% @transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.label :id %>
    <%= f.text_field :id, disabled: :disabled %>

    <%= f.label :debitor %>
    <%= f.text_field :debitor, disabled: :disabled %>

    <%= f.label :creditor %>
    <%= f.text_field :creditor, disabled: :disabled %>

    <%= f.label :amount %>
    <%= f.text_field :amount, disabled: disabled %>

    <%= f.label :category_id %>
    <%= f.select :category_id, grouped_category_options(selected: f.object.category_id), { include_blank: true }, { disabled: disabled } %>

    <%= f.label :note %>
    <%= f.text_area :note, disabled: disabled %>

    <div class="field">
      <%= f.label :booked_at %>
      <%= f.datetime_select :booked_at, {}, { disabled: disabled } %>
    </div>

    <div class="field">
      <%= f.label :interest_at %>
      <%= f.datetime_select :interest_at, {}, { disabled: disabled } %>
    </div>

    <% if Current.user.can_administer? %>
      <%= f.label :original_note %>
      <%= f.text_area :original_note, disabled: true %>

      <%= f.label :original_balance_after_mutation %>
      <%= f.text_field :original_balance_after_mutation, disabled: true %>

      <%= f.label :original_tag %>
      <%= f.text_field :original_tag, disabled: true %>
    <% end %>

    <% unless disabled %>
      <div class="actions">
        <%= f.submit %>
      </div>
    <% end %>
  <% end %>
</section>

app/views/transactions/_table.html.erb
<%= pagy_nav(pagy) %>

<table class="transactions">
  <thead>
    <tr>
      <th></th>
      <th><%= t('.type') %></th>
      <th><%= t('.creditor') %></th>
      <th><%= t('.debitor') %></th>
      <th><%= t('.amount') %></th>
      <th><%= t('.booked_at') %></th>
      <th><%= t('.interest_date') %></th>
      <th><%= t('.category') %></th>
      <th><%= t('.note') %></th>
    </tr>
  </thead>

  <tbody>
    <% transactions.each do |transaction| %>
      <tr>
        <td>
          <%= link_to transaction do %>
            <b><%= t('.show') %></b>
          <% end %>
        </td>
        <td><%= transaction.type_icon %></td>
        <% creditor = transaction.creditor %>
        <td><%= creditor ? link_to(creditor.name || creditor.account_number, account_path(creditor)) : "" %></td>
        <% debitor = transaction.debitor %>
        <td><%= debitor ? link_to(debitor.name || debitor.account_number, account_path(debitor)) : "" %></td>
        <td><%= number_to_currency transaction&.amount %></td>
        <td><%= l transaction&.booked_at %></td>
        <td><%= l transaction&.interest_at %></td>
        <td><%= transaction&.category&.to_s %></td>
        <td><%= transaction&.note&.truncate(20) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= pagy_nav(pagy) %>

app/views/transactions/edit.html.haml
= content_for(:secondary_nav) do
  %nav.secondary
    %ul
      %li= link_to 'All transactions', transactions_path
      %li= link_to 'Consolidatable', transactions_path(filter: :no_category)
%h1
  = "#{@transaction.creditor} ➡️ #{@transaction.debitor}"
  = link_to @transaction do
    %b Show

= render partial: 'form'

%section
  = link_to @transaction, method: :delete, data: { confirm: 'Are you sure?' } do
    %b Destroy

app/views/transactions/index.html.erb
<section class="transactions">
  <%= render partial: 'table', locals: { transactions: @transactions, pagy: @pagy } %>
</section>

<section class="actions">
  <aside>
    <%= link_to new_transaction_path do %>
      <strong><%= t('.new_transaction') %></strong>
    <% end %>
  </aside>

  <%= form_with local: true, url: transactions_imports_path, multipart: true do |form| %>
    <%= form.file_field :csv %>
    <%= form.submit t('.upload') %>
  <% end %>
</section>

app/views/transactions/new.html.haml
= content_for(:secondary_nav) do
  %nav.secondary
    %ul
      %li= link_to 'Back', :back

%h1 New transaction
= render 'form'

app/views/transactions/show.html.erb
<% content_for(:secondary_nav) do %>
  <nav class="secondary">
    <ul>
      <li><%= link_to t(".all_transactions"), transactions_path %></li>
      <li><%= link_to t(".consolidatable"), transactions_path(filter: :no_category) %></li>
    </ul>
  </nav>
<% end %>

<h1>
  <%= "#{@transaction.creditor} ➡️ #{@transaction.debitor}" %>
  <%= link_to edit_transaction_path(@transaction) do %>
    <b><%= t(".edit") %></b>
  <% end %>
</h1>

<%= render partial: 'form', locals: { disabled: :disabled } %>

<h2><%= t(".mutations") %></h2>

<table>
  <thead>
    <tr>
      <th><%= t(".account") %></th>
      <th><%= t(".amount") %></th>
    </tr>
  </thead>
  <tbody>
    <% @transaction.mutations.each do |mutation| %>
      <tr>
        <td><%= link_to mutation.account, account_path(mutation.account) %></td>
        <td><%= number_to_currency mutation.amount %></td>
      </tr>
    <% end %>
  </tbody>
</table>