config/routes.rb
Rails.application.routes.draw do
  mount Faultline::Engine, at: "/faultline"

  namespace :admin do
    root "dashboard#index"
    resources :users
  end

  resources :chattels
  root "dashboard#index"

  resource :session, only: %i[ new create destroy ] do
    scope module: "sessions" do
      resources :transfers, only: %i[ show update ]
    end
  end

  resources :users do
    scope module: "users" do
      resource :profile
    end
  end

  resources :transactions
  namespace :transactions do
    resources :imports, only: [ :create ]
  end
  resources :credit, controller: "transactions", type: "Transaction"
  resources :debit, controller: "transactions", type: "Transaction"
  resources :transfer, controller: "transactions", type: "Transaction"
  resources :accounts do
    scope module: "accounts" do
      resource :transactions_bulk, only: [ :update ]
    end
  end
  resources :categories
  get "dashboard/index"
  get "todo", to: "todos#index", as: :todo

  get "up" => "rails/health#show", as: :rails_health_check
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/account.rb
# Represents a bank account with transactions and categorization
#
# Accounts can be family-owned (samen, etienne, michelle, serena, cosimo, chiara) or external
# (e.g., Albert Heijn, creditors, other banks). The owner enum determines whether
# transactions are debits, credits, or transfers.
class Account < ApplicationRecord
  include Normalizable
  include Resolvable
  include BulkUpdatable

  FAMILY_OWNERS = %w[samen etienne michelle serena cosimo chiara].freeze

  # @!attribute [rw] owner
  #   @return [String] The account owner (samen, etienne, michelle, serena, cosimo, chiara)
  enum :owner,        { samen: 0, etienne: 1, michelle: 2, serena: 3, cosimo: 4, chiara: 5 }
  enum :account_type, { asset: 0, liability: 1, expense: 2, income: 3 }

  belongs_to :category, optional: true

  validates :account_number, uniqueness: true, allow_blank: true

  # Returns human-readable string representation of the account
  #
  # @return [String] Account name if present, otherwise account number
  def to_s
    return name unless name.blank?

    account_number
  end
end

app/controllers/accounts/transactions_bulk_controller.rb
# Bulk updates to uncategorized transactions for an account
class Accounts::TransactionsBulkController < ApplicationController
  before_action :set_account

  # Updates all uncategorized transactions in an account to the account's category
  #
  # @return [void]
  def update
    updated_count = @account.update_uncategorized_transactions!
    flash[:notice] = "#{updated_count} transactions updated to category #{@account.category.name}."
    redirect_back fallback_location: accounts_url
  rescue BulkUpdatable::MissingCategoryError
    redirect_back fallback_location: accounts_url, alert: "Account has no category"
  end

  private

  def set_account
    @account = Account.find(params[:account_id])
  end
end

app/controllers/accounts_controller.rb
# Manages account resources
class AccountsController < ApplicationController
  before_action :set_account, only: %i[show edit update destroy]

  # Lists all accounts with pagination
  #
  # @return [void]
  def index
    @pagy, @records = pagy Account.all
  end

  # Displays a single account
  #
  # @return [void]
  def show; end

  # Renders form for creating a new account
  #
  # @return [void]
  def new
    @account = Account.new
  end

  # Renders form for editing an account
  #
  # @return [void]
  def edit; end

  # Creates a new account
  #
  # @return [void]
  def create
    @account = Account.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to @account, notice: "Account was successfully created." }
        format.json { render :show, status: :created, location: @account }
      else
        format.html { render :new }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # Updates an account
  #
  # @return [void]
  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to @account, notice: "Account was successfully updated." }
        format.json { render :show, status: :ok, location: @account }
      else
        format.html { render :edit }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  # Deletes an account
  #
  # @return [void]
  def destroy
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_url, notice: "Account was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_account
    @account = Account.find(params[:id])
  end

  def account_params
    params.require(:account).permit(:id, :account_number, :name, :owner, :category_id)
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.haml
= form_for @account do |f|
  - if @account.errors.any?
    #error_explanation
      %h2= "#{pluralize(@account.errors.count, "error")} prohibited this account from being saved:"
      %ul
        - @account.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :id
    = f.text_field :id, disabled: :disabled
  .field
    = f.label :account_number
    = f.text_field :account_number
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :owner
    = f.collection_select :owner, Account.owners, :first, :first, { include_blank: true }
  .field
    = f.label :category_id
    = f.collection_select :category_id, Category.all.order(:name), :id, :name, { include_blank: true }
  .actions
    = f.submit 'Save'

app/views/accounts/edit.html.haml
%h1
  = @account.name
  = link_to @account do
    %b Show
= render 'form'

app/views/accounts/index.html.erb
<section>
  <%= pagy_nav(@pagy) %>

  <table class="accounts">
    <thead>
      <tr>
        <th></th>
        <th><%= t('.id') %></th>
        <th><%= t('.account_number') %></th>
        <th><%= t('.name') %></th>
        <th><%= t('.owner') %></th>
        <th><%= t('.category') %></th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @records.each do |account| %>
        <tr>
          <td>
            <%= link_to account do %>
              <b><%= t('.show') %></b>
            <% end %>
          </td>
          <td><%= account.id %></td>
          <td><%= account.account_number %></td>
          <td><%= account.name %></td>
          <td><%= account.owner %></td>
          <td><%= account.category&.name %></td>
          <td><%= link_to t('.edit'), edit_account_path(account) %></td>
          <td><%= button_to t('.update_transactions'), account_transactions_bulk_path(account), method: :patch %></td>
          <td><%= button_to t('.destroy'), account, method: :delete, data: { turbo_confirm: t('.confirm_destroy') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= pagy_nav(@pagy) %>

</section>

<section>
  <%= link_to new_account_path do %>
    <b><%= t('.new_account') %></b>
  <% end %>
</section>

app/views/accounts/new.html.haml
%h1 New account
= render 'form'

app/views/accounts/show.html.erb
<h1>
  <%= @account.name %>
  <%= link_to edit_account_path(@account) do %>
    <b><%= t('.edit') %></b>
  <% end %>
</h1>

<p>
  <b><%= t('.id') %></b>
  <%= @account.id %>
</p>
<p>
  <b><%= t('.account_number') %></b>
  <%= @account.account_number %>
</p>
<p>
  <b><%= t('.name') %></b>
  <%= @account.name %>
</p>
<p>
  <b><%= t('.owner') %></b>
  <%= @account.owner %>
</p>
<p>
  <b><%= t('.category') %></b>
  <%= @account.category&.name %>
</p>

<%= button_to t('.update_transactions'), account_transactions_bulk_path(@account), method: :patch %>